<a href="https://colab.research.google.com/github/AllEternal/Hamoye-Lessons-and-Quiz/blob/master/NumPy_Array_and_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Convention For Importing Numpy

In [ ]:
import numpy as np

In [ ]:
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.dtype)

int64


# Get The Dimension of a with ndim

In [ ]:
print(a.ndim)

1


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.ndim)

2


In [ ]:
b.shape

(2, 3)

In [ ]:
import numpy as np

In [ ]:
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.dtype)

int64


# Get Dimention of a with ndim

In [ ]:
print(a.ndim)

1


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.ndim)

2


In [ ]:
b.shape

(2, 3)

# Inbuilt Functions to Initialize NumPy

# a 2x3 array with random values

In [ ]:
np.random.random((2, 3))

array([[0.66065727, 0.47709221, 0.76765276],
       [0.39721795, 0.87421842, 0.94617759]])

# a 2x3 array of zeros

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# a 2x3 array of ones

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# a 2x3 arrays of ones

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# a 3x3 identity matrix

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Intra-Operability of arrays and Scalers

In [ ]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [ ]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [ ]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [ ]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [ ]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

# Indexing With Arrays and Using Arrays For Data processing

In [ ]:
a[0]

6

In [ ]:
a[3]

9

In [ ]:
b[0,0]

1

In [ ]:
b[1, 2]

6

In [ ]:
c[0, 1]

8.0

In [ ]:
d[1, 0:2]

array([9., 8.])

In [ ]:
e = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]])

# slicing

In [ ]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

# Integer Indexing

In [ ]:
e[[2, 0, 3, 1], [2, 1, 0, 2]]

array([18, 11, 19, 15])

# Boolean Indexing Meeting a Specific Condition

In [ ]:
e[e>15]

array([16, 17, 18, 19, 20, 21])